import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/organism/global/Navbar";
import { ReactLenis } from 'lenis/react'

const switzer = localFont({
  src: [
    { path: "../assets/fonts/Switzer-Thin.woff2", weight: "100", style: "normal" },
    { path: "../assets/fonts/Switzer-ThinItalic.woff2", weight: "100", style: "italic" },

    { path: "../assets/fonts/Switzer-Extralight.woff2", weight: "200", style: "normal" },
    { path: "../assets/fonts/Switzer-ExtralightItalic.woff2", weight: "200", style: "italic" },

    { path: "../assets/fonts/Switzer-Light.woff2", weight: "300", style: "normal" },
    { path: "../assets/fonts/Switzer-LightItalic.woff2", weight: "300", style: "italic" },

    { path: "../assets/fonts/Switzer-Regular.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/Switzer-Italic.woff2", weight: "400", style: "italic" },

    { path: "../assets/fonts/Switzer-Medium.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/Switzer-MediumItalic.woff2", weight: "500", style: "italic" },

    { path: "../assets/fonts/Switzer-Semibold.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/Switzer-SemiboldItalic.woff2", weight: "600", style: "italic" },

    { path: "../assets/fonts/Switzer-Bold.woff2", weight: "700", style: "normal" },
    { path: "../assets/fonts/Switzer-BoldItalic.woff2", weight: "700", style: "italic" },

    { path: "../assets/fonts/Switzer-Extrabold.woff2", weight: "800", style: "normal" },
    { path: "../assets/fonts/Switzer-ExtraboldItalic.woff2", weight: "800", style: "italic" },

    { path: "../assets/fonts/Switzer-Black.woff2", weight: "900", style: "normal" },
    { path: "../assets/fonts/Switzer-BlackItalic.woff2", weight: "900", style: "italic" },
  ],
  variable: "--font-switzer",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} antialiased`}
      >
        <ReactLenis
          root
          options={{
            lerp: 0.1,          // semakin kecil => semakin smooth (0.1–0.2 enak)
            duration: 1.4,      // durasi interpolasi scroll
            smoothWheel: true,  // aktifkan smooth untuk wheel (mouse)
            touchMultiplier: 1.5, // percepat swipe di mobile
            wheelMultiplier: 1,   // percepat/lamain scroll wheel
            syncTouch: false,     // kalau true, drag jari langsung sync ke scroll
          }}
        >
          <Navbar />
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
